name: Build and deploy Node.js app to Azure Web App - employee-onboarding

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Set up Node.js version and ensure correct version is used
      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.20.3'  # Match your local version

      # Clean npm cache (in case of dependency conflicts)
      - name: Clean npm cache
        run: npm cache clean --force

      # Install dependencies for client (React app)
      - name: Install dependencies for client (React app)
        run: |
          cd client
          npm install

      # Build React app
      - name: Build React app
        run: |
          cd client
          npm run build

      # Install dependencies for server (Express app)
      - name: Install dependencies for server (Express app)
        run: |
          cd server
          npm install

      # Zip frontend (client) and backend (server) artifacts for deployment
      - name: Zip frontend and backend artifacts
        run: |
          zip -r release.zip ./client/dist ./server  # Ensure both frontend and backend are included

      # Upload artifact for deployment job
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: 'https://employee-onboarding-frapguepdzd0e9dg.northeurope-01.azurewebsites.net/'
    permissions:
      id-token: write

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      # Login to Azure using the provided credentials
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # Deploy to Azure Web App
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'employee-onboarding'
          slot-name: 'production'
          package: .  # Deploy from the root folder, which contains both the frontend and backend
